import type { Product } from "./types.ts";
export const products: readonly Product[] = [
  { id:"prod_kordena", name:"Kordena", slug:"kordena", group:"Produtos principais", lifecycle:"principal", publicLabel:"Produto Principal", shortDescription:"Uma base tecnológica para organizar operações com mais clareza e inteligência.", positioning:"Organização e inteligência para operações que querem avançar.", pricing:{monthly:299,annual:2990,enterprise:true}, trial:{days:30,cardRequired:false}, cta:{trial:true,specialist:true}, featured:true, commercialStatus:"trial-disponivel", seo:{title:"Kordena",description:"Conheça o Kordena, produto principal da FM Tecnologia."}},
  { id:"prod_iron_fit", name:"Iron Fit", slug:"iron-fit", group:"Produtos principais", lifecycle:"principal", publicLabel:"Produto Principal", shortDescription:"Tecnologia criada para apoiar a evolução da gestão de negócios fitness.", positioning:"Gestão inteligente para negócios fitness.", pricing:{monthly:269,annual:2690,enterprise:true}, trial:{days:30,cardRequired:false,constraint:"Máximo de 15 alunos durante o teste."}, cta:{trial:true,specialist:true}, featured:true, commercialStatus:"trial-disponivel", seo:{title:"Iron Fit",description:"Conheça o Iron Fit, produto principal da FM Tecnologia."}},
  { id:"prod_vendedor_ia", name:"Vendedor IA", slug:"vendedor-ia", group:"Em desenvolvimento", lifecycle:"desenvolvimento", publicLabel:"Em desenvolvimento · Em breve", shortDescription:"Uma nova frente de tecnologia para apoiar jornadas comerciais.", positioning:"Inteligência aplicada à evolução comercial.", cta:{trial:false,specialist:true}, featured:false, commercialStatus:"em-breve", seo:{title:"Vendedor IA",description:"Conheça o Vendedor IA, em desenvolvimento pela FM Tecnologia."}},
  { id:"prod_campaia", name:"CampaIA", slug:"campaia", group:"Em desenvolvimento", lifecycle:"desenvolvimento", publicLabel:"Em desenvolvimento · Em breve", shortDescription:"Tecnologia em construção para novas experiências de comunicação.", positioning:"Inteligência para jornadas de comunicação.", cta:{trial:false,specialist:true}, featured:false, commercialStatus:"em-breve", seo:{title:"CampaIA",description:"Conheça o CampaIA, em desenvolvimento pela FM Tecnologia."}},
  { id:"prod_super_core", name:"Super Core Extreme", slug:"super-core-extreme", group:"Tecnologia & P&D", lifecycle:"pesquisa", publicLabel:"Tecnologia & P&D · Em desenvolvimento", shortDescription:"Iniciativa de pesquisa e desenvolvimento do ecossistema FM.", positioning:"Exploração tecnológica para o futuro do ecossistema.", cta:{trial:false,specialist:false}, featured:false, commercialStatus:"nao-comercial", seo:{title:"Super Core Extreme",description:"Tecnologia e P&D em desenvolvimento na FM Tecnologia."}},
  { id:"prod_erp_core", name:"ERP Core", slug:"erp-core", group:"Em desenvolvimento", lifecycle:"desenvolvimento", publicLabel:"Em desenvolvimento · Em breve", shortDescription:"Uma fundação em desenvolvimento para operações integradas.", positioning:"Base tecnológica para operações conectadas.", cta:{trial:false,specialist:true}, featured:false, commercialStatus:"em-breve", seo:{title:"ERP Core",description:"Conheça o ERP Core, em desenvolvimento pela FM Tecnologia."}}
] as const satisfies readonly Product[];
export type ProductSlug = (typeof products)[number]["slug"];
export function getProduct(slug: string): Product | undefined { return products.find((product) => product.slug === slug); }
export function getProductsByGroup(group: Product["group"]): Product[] { return products.filter((product) => product.group === group); }
