import type { Product } from "./types.ts";

const pending = "pending_evidence" as const;

export const products: readonly Product[] = [
  {
    id: "prod_kordena",
    name: "Kordena",
    slug: "kordena",
    group: "Produtos Principais",
    priority: "primary",
    lifecycle: pending,
    websiteVisibility: "public",
    technicalReadiness: pending,
    certificationStatus: pending,
    commercialAvailability: pending,
    trialPolicyStatus: "approved_partial_contract",
    trialReleaseStatus: pending,
    pricingStatus: "approved",
    productionHomologationStatus: pending,
    publicLabel: "Produto Principal",
    shortDescription: "Gestão e inteligência para restaurantes: atendimento, produção, cardápio, estoque, financeiro e clientes.",
    positioning: "Plataforma de gestão e inteligência para restaurantes.",
    pricing: { monthly: 299, annual: 2990, enterprise: true },
    trialPolicy: { days: 30, cardRequired: false },
    cta: { specialist: true },
    featured: true,
    seo: { title: "Kordena", description: "Gestão e inteligência para restaurantes: atendimento, produção, cardápio, estoque, financeiro e clientes." },
  },
  {
    id: "prod_iron_fit",
    name: "Iron Fit",
    slug: "iron-fit",
    group: "Produtos Principais",
    priority: "primary",
    lifecycle: pending,
    websiteVisibility: "public",
    technicalReadiness: pending,
    certificationStatus: pending,
    commercialAvailability: pending,
    trialPolicyStatus: "approved_partial_contract",
    trialReleaseStatus: pending,
    pricingStatus: "approved",
    productionHomologationStatus: pending,
    publicLabel: "Produto Principal",
    shortDescription: "Alunos, treinos, agenda e check-in para conectar a academia à rotina do aluno.",
    positioning: "Produto principal da FM Tecnologia.",
    pricing: { monthly: 269, annual: 2690, enterprise: true },
    trialPolicy: {
      days: 30,
      cardRequired: false,
      constraint: "Máximo de 15 alunos durante o teste.",
    },
    cta: { specialist: true },
    featured: true,
    seo: { title: "Iron Fit", description: "Alunos, treinos, agenda e check-in para conectar a academia à rotina do aluno." },
  },
  {
    id: "prod_vendedor_ia",
    name: "Vendedor IA",
    slug: "vendedor-ia",
    group: "O que estamos construindo",
    priority: "standard",
    lifecycle: "in_development",
    websiteVisibility: "public",
    technicalReadiness: pending,
    certificationStatus: pending,
    commercialAvailability: "unavailable",
    trialPolicyStatus: "not_available",
    trialReleaseStatus: "unavailable",
    pricingStatus: "not_for_public_offer",
    productionHomologationStatus: pending,
    publicLabel: "Em desenvolvimento · Em breve",
    shortDescription: "Projeto em desenvolvimento pela FM Tecnologia.",
    positioning: "Projeto em desenvolvimento. Mais informações serão publicadas em breve.",
    cta: { specialist: true },
    featured: false,
    seo: { title: "Vendedor IA", description: "Vendedor IA, em desenvolvimento pela FM Tecnologia." },
  },
  {
    id: "prod_campaia",
    name: "CampaIA",
    slug: "campaia",
    group: "O que estamos construindo",
    priority: "standard",
    lifecycle: "in_development",
    websiteVisibility: "public",
    technicalReadiness: pending,
    certificationStatus: pending,
    commercialAvailability: "unavailable",
    trialPolicyStatus: "not_available",
    trialReleaseStatus: "unavailable",
    pricingStatus: "not_for_public_offer",
    productionHomologationStatus: pending,
    publicLabel: "Em desenvolvimento · Em breve",
    shortDescription: "Projeto em desenvolvimento pela FM Tecnologia.",
    positioning: "Projeto em desenvolvimento. Mais informações serão publicadas em breve.",
    cta: { specialist: true },
    featured: false,
    seo: { title: "CampaIA", description: "CampaIA, em desenvolvimento pela FM Tecnologia." },
  },
  {
    id: "prod_super_core",
    name: "Super Core Extreme",
    slug: "super-core-extreme",
    group: "Tecnologia & P&D",
    priority: "standard",
    lifecycle: "research_and_development",
    websiteVisibility: "public",
    technicalReadiness: pending,
    certificationStatus: pending,
    commercialAvailability: "unavailable",
    trialPolicyStatus: "not_available",
    trialReleaseStatus: "unavailable",
    pricingStatus: "not_for_public_offer",
    productionHomologationStatus: pending,
    publicLabel: "Tecnologia & P&D · Em desenvolvimento",
    shortDescription: "Tecnologia e pesquisa em desenvolvimento pela FM Tecnologia.",
    positioning: "Plataforma estratégica de Pesquisa & Desenvolvimento da FM Tecnologia.",
    cta: { specialist: false },
    featured: false,
    seo: { title: "Super Core Extreme", description: "Tecnologia e P&D em desenvolvimento na FM Tecnologia." },
  },
  {
    id: "prod_erp_core",
    name: "ERP Core",
    slug: "erp-core",
    group: "O que estamos construindo",
    priority: "standard",
    lifecycle: "in_development",
    websiteVisibility: "public",
    technicalReadiness: pending,
    certificationStatus: pending,
    commercialAvailability: "unavailable",
    trialPolicyStatus: "not_available",
    trialReleaseStatus: "unavailable",
    pricingStatus: "not_for_public_offer",
    productionHomologationStatus: pending,
    publicLabel: "Em desenvolvimento · Em breve",
    shortDescription: "Projeto em desenvolvimento pela FM Tecnologia.",
    positioning: "Projeto em desenvolvimento. Mais informações serão publicadas em breve.",
    cta: { specialist: true },
    featured: false,
    seo: { title: "ERP Core", description: "ERP Core, em desenvolvimento pela FM Tecnologia." },
  },
] as const satisfies readonly Product[];

export type ProductSlug = (typeof products)[number]["slug"];

export function getProduct(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug);
}

export function getProductsByGroup(group: Product["group"]): Product[] {
  return products.filter((product) => product.group === group);
}
