import Image from "next/image";
import Link from "next/link";
import { siteConfig } from "@/src/config/site";
import { IronFitIntelligenceEcosystemSecurity } from "./iron-fit-intelligence-ecosystem-security";
import { IronFitConversionFinal } from "./iron-fit-conversion-final";

const domains = ["Aluno", "Treino", "Avaliação", "Equipamentos", "Agenda", "Acesso", "Financeiro", "Inteligência"] as const;
const managementItems = [["Alunos", "Cadastros, situação e contexto do aluno reunidos para a equipe autorizada."],["Treinos", "Prescrições, sessões e exercícios conectados à jornada de cada aluno."],["Agenda", "Horários, reservas e presença organizados no mesmo ambiente operacional."],["Acessos", "Check-in e controles de entrada ligados ao contexto da academia e do aluno."],["Equipamentos", "Inventário da unidade conectado ao catálogo mestre e aos exercícios."],["Financeiro", "Cobranças, recebimentos, pendências e visão de receita acompanhando a operação."]] as const;
const studentItems = ["Treinos e exercícios", "Agenda", "Check-in", "Avaliações e evolução", "Financeiro", "Perfil e unidade ativa"] as const;
const trainingFlow = ["Avaliação", "Prescrição", "Treino", "Acompanhamento", "Evolução"] as const;
const officialLockup = "/iron-fit-core-official-lockup.webp";

export function IronFitCoreLanding() {
  const message = "Olá! Quero conhecer o Iron Fit Core e entender a disponibilidade para minha academia.";
  const whatsapp = `https://wa.me/${siteConfig.whatsapp.number}?text=${encodeURIComponent(message)}`;
  return <main className="ironfit-landing">
    <section className="ironfit-hero" aria-labelledby="ironfit-title"><div className="ironfit-grid" aria-hidden="true"/><div className="container ironfit-hero__inner"><Link className="back-link ironfit-back" href="/produtos">← Todos os produtos</Link><div className="ironfit-hero__grid"><div className="ironfit-hero__copy"><p className="eyebrow">Plataforma integrada para academias e operações fitness</p><h1 id="ironfit-title">IRON FIT <span>CORE</span></h1><p className="ironfit-tagline">Inteligência no centro. Evolução em movimento.</p><p className="lead">Gestão, operação e jornada do aluno conectadas em uma única plataforma — do treino e acesso ao financeiro.</p><p className="ironfit-support">A equipe acompanha a academia em um só ambiente; o aluno leva treinos, agenda, check-in, evolução e financeiro no aplicativo.</p><div className="actions ironfit-actions"><a className="button button--primary ironfit-primary" href="#core">Conhecer o Iron Fit <span aria-hidden="true">↓</span></a><a className="button button--secondary ironfit-secondary" href={whatsapp}>Falar com a FM <span aria-hidden="true">↗</span></a></div><p className="ironfit-byline">IRON FIT CORE · by FM Tecnologia · ironfitcore.com.br</p></div><div className="ironfit-hero__visual" aria-label="Identidade oficial do Iron Fit Core"><span className="ironfit-halo ironfit-halo--one" aria-hidden="true"/><span className="ironfit-halo ironfit-halo--two" aria-hidden="true"/><div className="ironfit-approved-lockup"><Image src={officialLockup} alt="Logomarca oficial Iron Fit Core — Inteligência no centro. Evolução em movimento. by FM Tecnologia" width={520} height={308} priority unoptimized/></div></div></div></div></section>
    <nav className="ironfit-index" aria-label="Nesta página: Iron Fit Core"><div className="container"><a href="#core">Core</a><a href="#gestao">Gestão</a><a href="#app">App</a><a href="#treinos">Treinos</a><a href="#inteligencia">Inteligência</a><a href="#seguranca">Segurança</a><a href="#demo">Demo</a><a href="#planos">Planos</a><a href="#duvidas">Dúvidas</a></div></nav>
    <section id="core" className="ironfit-core-section"><div className="container"><div className="ironfit-core-heading"><p className="eyebrow">Core Vertical FM Tecnologia</p><h2>Um Core para conectar toda a operação.</h2><p>O Iron Fit Core organiza gestão, operação e experiência do aluno sobre o mesmo contexto, conectando módulos e dados para reduzir controles isolados.</p></div><div className="ironfit-core-stage"><div className="ironfit-core-orbit" aria-hidden="true"><span className="orbit orbit--one"/><span className="orbit orbit--two"/><span className="orbit orbit--three"/></div><div className="ironfit-core-mark"><Image src={officialLockup} alt="Logomarca oficial do Iron Fit Core" width={520} height={308} unoptimized/></div><div className="ironfit-core-domains">{domains.map((domain,index)=><div key={domain} className={`ironfit-domain ironfit-domain--${index+1}`}><span>{String(index+1).padStart(2,"0")}</span>{domain}</div>)}</div></div><div className="ironfit-core-flow"><span>Core Vertical</span><i>→</i><span>Módulos conectados</span><i>→</i><span>Dados contextualizados</span><i>→</i><span>Gestão e evolução</span></div></div></section>
    <section id="gestao" className="ironfit-section ironfit-management"><div className="container ironfit-split"><div className="ironfit-copy-block"><p className="eyebrow">Gestão da academia</p><h2>Da recepção à gestão, tudo no mesmo fluxo.</h2><p>Alunos, treinos, agenda, acessos, equipamentos e financeiro trabalham sobre a mesma base para dar à equipe uma visão mais clara da operação.</p><div className="ironfit-mini-brand"><Image src={officialLockup} alt="Iron Fit Core by FM Tecnologia" width={260} height={154} unoptimized/></div></div><div className="ironfit-management-grid">{managementItems.map(([title,text],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section id="app" className="ironfit-section ironfit-student"><div className="container ironfit-student-grid"><div className="ironfit-phone"><div className="ironfit-phone__bar"><span/><span/></div><div className="ironfit-phone__brand"><Image src={officialLockup} alt="" width={220} height={130} unoptimized/><small>Experiência do aluno</small></div><div className="ironfit-phone__list">{studentItems.slice(0,4).map(item=><span key={item}>{item}</span>)}</div></div><div className="ironfit-copy-block"><p className="eyebrow">Experiência do aluno</p><h2>A academia acompanha. O aluno evolui.</h2><p>O aluno acessa sua jornada em um ambiente próprio, conectado à mesma base operacional utilizada pela academia.</p><div className="ironfit-chip-list">{studentItems.map(item=><span key={item}>{item}</span>)}</div><p className="ironfit-note">Mesmo quando recursos inteligentes opcionais estiverem indisponíveis, os fluxos essenciais continuam funcionando.</p></div></div></section>
    <section id="treinos" className="ironfit-section ironfit-training"><div className="container"><div className="ironfit-centered-heading"><p className="eyebrow">Treinos e avaliações</p><h2>Da avaliação à evolução, todo o treino no mesmo contexto.</h2><p>Avaliações, prescrições, sessões, exercícios e equipamentos se conectam ao histórico do aluno para apoiar um acompanhamento mais consistente.</p></div><div className="ironfit-training-flow">{trainingFlow.map((item,index)=><div key={item}><span>0{index+1}</span><strong>{item}</strong>{index<trainingFlow.length-1&&<i>→</i>}</div>)}</div><div className="ironfit-training-facts"><article><h3>Prescrição estruturada</h3><p>Objetivo, nível, frequência, sessões, exercícios, séries, repetições, intervalos e carga sugerida podem compor o treino.</p></article><article><h3>Controle profissional</h3><p>Estados de aprovação e validade preservam o controle humano sobre a prescrição e o acompanhamento.</p></article><article><h3>Contexto da academia</h3><p>Exercícios podem ser relacionados aos equipamentos disponíveis na unidade.</p></article></div></div></section>
    <section id="equipamentos" className="ironfit-section ironfit-equipment"><div className="container ironfit-split ironfit-split--reverse"><div className="ironfit-equipment-map"><div>CATÁLOGO<br/><strong>MESTRE</strong></div><span>Inventário da unidade</span><span>Exercícios compatíveis</span><span>Treinos</span></div><div className="ironfit-copy-block"><p className="eyebrow">Equipamentos</p><h2>O treino considera a estrutura real da academia.</h2><p>O catálogo mestre reduz cadastros repetitivos: a unidade seleciona os equipamentos disponíveis e conecta sua estrutura aos exercícios e treinos.</p><div className="ironfit-chip-list"><span>Catálogo mestre</span><span>Inventário por unidade</span><span>Equipamento ↔ exercício</span><span>Menos cadastro repetitivo</span></div></div></div></section>
    <section id="agenda-acesso" className="ironfit-section ironfit-operations"><div className="container"><div className="ironfit-centered-heading"><p className="eyebrow">Agenda e acesso</p><h2>Da reserva ao acesso, tudo conectado ao aluno.</h2><p>Horários, reservas, presença e regras de acesso trabalham no mesmo contexto operacional da academia.</p></div><div className="ironfit-operations-grid"><article><span>01</span><h3>Agenda</h3><p>Horários e reservas organizados para equipe e aluno.</p></article><article><span>02</span><h3>Check-in</h3><p>Registro de entrada com retorno claro sobre a solicitação.</p></article><article><span>03</span><h3>Presença</h3><p>Frequência conectada ao histórico operacional.</p></article><article><span>04</span><h3>Acesso</h3><p>Regras e permissões vinculadas ao contexto da academia.</p></article></div></div></section>
    <section id="financeiro" className="ironfit-section ironfit-finance"><div className="container ironfit-finance-grid"><div className="ironfit-copy-block"><p className="eyebrow">Financeiro</p><h2>Operação e financeiro no mesmo contexto.</h2><p>Mensalidades, cobranças, recebimentos, pendências e receita acompanham a jornada do aluno e a gestão da academia na mesma plataforma.</p></div><div className="ironfit-finance-panel"><div><span>Mensalidades</span><strong>Assinaturas e cobranças</strong></div><div><span>Recebimentos</span><strong>Pagamentos e transações</strong></div><div><span>Pendências</span><strong>Acompanhamento financeiro</strong></div><div><span>Gestão</span><strong>Visão de receita</strong></div></div></div></section>
    <IronFitIntelligenceEcosystemSecurity />
    <IronFitConversionFinal />
  </main>;
}
